# Pandas Data Types
Series and Data Frame

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). The axis labels are collectively referred to as the index. The basic method to create a Series is to call:

s = pd.Series(data, index=index)

Data can be -
a Python dict,

an ndarray,

a scalar value (like 5)



In [2]:
import pandas as pd
import numpy as np
simpleData=pd.Series(data=5,index=[0,1,2,3,4,5])

In [3]:
simpleData


0    5
1    5
2    5
3    5
4    5
5    5
dtype: int64

In [4]:
s=pd.Series(data=[2,34,5,8,0])

In [5]:
s

0     2
1    34
2     5
3     8
4     0
dtype: int64

In [6]:
DictA={'Today':6,'is':'Oct','Awesome':2021}

In [7]:
series2=pd.Series(DictA)

In [8]:
series2

Today         6
is          Oct
Awesome    2021
dtype: object

In [9]:
Dict2={'a':22,'b':44,'c':66}
series3=pd.Series(Dict2)

In [10]:
series3

a    22
b    44
c    66
dtype: int64

In [11]:
series3=pd.Series(Dict2,index=['c','d','a','b'])

In [12]:
series3

c    66.0
d     NaN
a    22.0
b    44.0
dtype: float64

In [13]:
series4={'a':33.566,'b':21.78,'c':41.097,'d':37.555,'e':25.003}

In [14]:
s4=pd.Series(series4)

In [15]:
s4

a    33.566
b    21.780
c    41.097
d    37.555
e    25.003
dtype: float64

In [16]:
s4[0]

33.566

In [17]:
s4[:3]

a    33.566
b    21.780
c    41.097
dtype: float64

In [18]:
s4[[4,3,1]]

e    25.003
d    37.555
b    21.780
dtype: float64

In [19]:
s4.dtype

dtype('float64')

In [20]:
s5=s4.array
s5

<PandasArray>
[33.566, 21.78, 41.097, 37.555, 25.003]
Length: 5, dtype: float64

In [21]:
s4.median()

33.566

In [22]:
s4.mean()

31.800200000000007

In [23]:
np.exp(s4)

a    3.780320e+14
b    2.876960e+09
c    7.050182e+17
d    2.041405e+16
e    7.222124e+10
dtype: float64

In [24]:
s4.dtype

dtype('float64')

In [25]:
s4.array

<PandasArray>
[33.566, 21.78, 41.097, 37.555, 25.003]
Length: 5, dtype: float64

In [26]:
#While Series is ndarray-like, if you need an actual ndarray, then use Series.to_numpy().
s4.to_numpy()

array([33.566, 21.78 , 41.097, 37.555, 25.003])

In [27]:
s4['e']

25.003

In [28]:
'd' in s4

True

In [29]:
'h' in s4

False

In [30]:
s4["a"]

33.566

In [31]:
s4.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [32]:
s4.values

array([33.566, 21.78 , 41.097, 37.555, 25.003])

In [33]:
s4.items

<bound method Series.iteritems of a    33.566
b    21.780
c    41.097
d    37.555
e    25.003
dtype: float64>

In [34]:
s6=pd.Series(s4.keys())
s6

0    a
1    b
2    c
3    d
4    e
dtype: object

In [35]:
s7=s4.to_numpy()

In [36]:
s7

array([33.566, 21.78 , 41.097, 37.555, 25.003])

In [37]:
s7+s7

array([67.132, 43.56 , 82.194, 75.11 , 50.006])

In [38]:
s7*3

array([100.698,  65.34 , 123.291, 112.665,  75.009])

In [39]:
s4+s4

a    67.132
b    43.560
c    82.194
d    75.110
e    50.006
dtype: float64

In [40]:
np.exp(s4)

a    3.780320e+14
b    2.876960e+09
c    7.050182e+17
d    2.041405e+16
e    7.222124e+10
dtype: float64

In [41]:
s4[1:]

b    21.780
c    41.097
d    37.555
e    25.003
dtype: float64

In [42]:
s4[:-1]

a    33.566
b    21.780
c    41.097
d    37.555
dtype: float64

In [43]:
s4[1:]+s4[:-1]

a       NaN
b    43.560
c    82.194
d    75.110
e       NaN
dtype: float64

In [44]:
s7[1:]

array([21.78 , 41.097, 37.555, 25.003])

In [45]:
s7[:-1]

array([33.566, 21.78 , 41.097, 37.555])

In [46]:
s7[1:]+s7[:-1]

array([55.346, 62.877, 78.652, 62.558])

In [47]:
#Name Attribute

In [48]:
sample=pd.Series(np.random.randn(5), name='Hey')

In [49]:
sample

0    0.266282
1   -0.504701
2   -0.935207
3    0.804870
4   -0.757091
Name: Hey, dtype: float64

In [50]:
sample2=pd.Series(data=(1,2,3), name='You')
sample2.name

'You'

In [51]:
sample2.rename('Me')

0    1
1    2
2    3
Name: Me, dtype: int64

In [52]:
sample2.name

'You'

# Data Frame

In [53]:
#From dict of series or dicts
import pandas as pd

In [54]:
d={'Monday':pd.Series([1,2,3,4], index=['a','b','c','d']),
  'Tuesday':pd.Series([3,6,9,12,15],index=['a','b','c','d','e'])}

In [55]:
DF=pd.DataFrame(d)

In [56]:
DF

Monday  Tuesday
a     1.0        3
b     2.0        6
c     3.0        9
d     4.0       12
e     NaN       15

In [57]:
pd.DataFrame(d,index=['e','d','c','b','a'])

Monday  Tuesday
e     NaN       15
d     4.0       12
c     3.0        9
b     2.0        6
a     1.0        3

In [58]:
DF

Monday  Tuesday
a     1.0        3
b     2.0        6
c     3.0        9
d     4.0       12
e     NaN       15

In [59]:
pd.DataFrame(d,index=['e','d','c','b','a'], columns=['Monday','Tuesday','two'])

Monday  Tuesday  two
e     NaN       15  NaN
d     4.0       12  NaN
c     3.0        9  NaN
b     2.0        6  NaN
a     1.0        3  NaN

In [60]:
DF.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [61]:
DF.columns


Index(['Monday', 'Tuesday'], dtype='object')

In [62]:
DF.head(3)

Monday  Tuesday
a     1.0        3
b     2.0        6
c     3.0        9

In [63]:
DF.tail(3)

Monday  Tuesday
c     3.0        9
d     4.0       12
e     NaN       15

In [64]:
#from dict of ndarrays or lists
d={'one':[1,3,5,7,9],'two':[2,4,6,8,10]}

In [65]:
pd.DataFrame(d)

one  two
0    1    2
1    3    4
2    5    6
3    7    8
4    9   10

In [66]:
pd.DataFrame(d,index=['a','b','c','d','e'])

one  two
a    1    2
b    3    4
c    5    6
d    7    8
e    9   10

In [67]:
#from structured or record array
import numpy as np
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "a10")])
data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]

In [68]:
pd.DataFrame(data)

A    B         C
0  1  2.0  b'Hello'
1  2  3.0  b'World'

In [69]:
pd.DataFrame(data,index=['first','second'])

A    B         C
first   1  2.0  b'Hello'
second  2  3.0  b'World'

In [70]:
pd.DataFrame(data,columns=['C','B','A','D'])

C    B  A    D
0  b'Hello'  2.0  1  NaN
1  b'World'  3.0  2  NaN

In [71]:
#from list of dict
data2=[{'a':1,'b':2},{'a':5,'b':7,'c':9}]


In [72]:
pd.DataFrame(data2)

a  b    c
0  1  2  NaN
1  5  7  9.0

In [73]:
pd.DataFrame(data2,index=['first','second'])


a  b    c
first   1  2  NaN
second  5  7  9.0

In [74]:
pd.DataFrame(data2,columns=['a','b'])

a  b
0  1  2
1  5  7

In [75]:
#from a dict of tuples
pd.DataFrame(
    {
        ("a", "b"): {("A", "B"): 1, ("A", "C"): 2},
        ("a", "b"): {("A", "B"): 5, ("A", "C"): 6},
    }
)

a
     b
A B  5
  C  6

In [76]:
#from list of named tuple
from collections import namedtuple
Point= namedtuple("Point","x y")
pd.DataFrame([Point(0,0),Point(2,3),Point(5,8)])

x  y
0  0  0
1  2  3
2  5  8

In [77]:
import pandas as pd
from collections import namedtuple
Point=namedtuple('Point',("x y"))
pd.DataFrame([Point(3,6), Point(7,8)])

x  y
0  3  6
1  7  8

In [78]:
#from list of dataclasses
from dataclasses import make_dataclass

Point = make_dataclass("Point", (("x", int), ("y", int)))

pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])



0
0  Point(x=0, y=0)
1  Point(x=0, y=3)
2  Point(x=2, y=3)

In [79]:
#Alternate Constructors
pd.DataFrame.from_dict(dict([('A',[3,5,7]),('B',[2,4,6])]))

A  B
0  3  2
1  5  4
2  7  6

In [80]:
pd.DataFrame.from_dict(dict([('A',[3,5,7]),('B',[2,4,6])]),orient='index')

0  1  2
A  3  5  7
B  2  4  6

In [81]:
pd.DataFrame.from_dict(dict([('A',[3,5,7]),('B',[2,4,6])]),orient='index',columns=['one','two','three'])

one  two  three
A    3    5      7
B    2    4      6

In [82]:
import numpy as np
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "a10")])

data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]
data

array([(1, 2., b'Hello'), (2, 3., b'World')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [83]:
pd.DataFrame.from_records(data,index='C')

A    B
C               
b'Hello'  1  2.0
b'World'  2  3.0

In [84]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [85]:
df=pd.DataFrame(d)

In [86]:
df["one"]

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [87]:
df['three']=df['one']*df['two']

In [88]:
df['flag']=df['one']>2

In [89]:
df

one  two  three   flag
a  1.0  1.0    1.0  False
b  2.0  2.0    4.0  False
c  3.0  3.0    9.0   True
d  NaN  4.0    NaN  False

In [90]:
#del df['two']

In [91]:
three= df.pop ('three')
df

one  two   flag
a  1.0  1.0  False
b  2.0  2.0  False
c  3.0  3.0   True
d  NaN  4.0  False

In [92]:
df['foo']='Code'
df

one  two   flag   foo
a  1.0  1.0  False  Code
b  2.0  2.0  False  Code
c  3.0  3.0   True  Code
d  NaN  4.0  False  Code

In [93]:
df['New']=df['one'][0:3]
df

one  two   flag   foo  New
a  1.0  1.0  False  Code  1.0
b  2.0  2.0  False  Code  2.0
c  3.0  3.0   True  Code  3.0
d  NaN  4.0  False  Code  NaN

In [94]:
#inserting new column at perticular location
df.insert(1,'bar',df["one"])
df

one  bar  two   flag   foo  New
a  1.0  1.0  1.0  False  Code  1.0
b  2.0  2.0  2.0  False  Code  2.0
c  3.0  3.0  3.0   True  Code  3.0
d  NaN  NaN  4.0  False  Code  NaN

In [95]:
#indexing/selection
DataIris=pd.read_csv("E:/01Learnwell Data/Python Datasets/Classification Datasets/IRIS.csv")

In [96]:
DataIris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [97]:
DataIris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
Sepal.Length    150 non-null float64
Sepal.Width     150 non-null float64
Petal.Length    150 non-null float64
Petal.Width     150 non-null float64
Species         150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [98]:
DataIris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [99]:
DataIris.assign(Sepal_Ratio=DataIris['Sepal.Width']/DataIris['Sepal.Length']).head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  Sepal_Ratio
0           5.1          3.5           1.4          0.2  setosa     0.686275
1           4.9          3.0           1.4          0.2  setosa     0.612245
2           4.7          3.2           1.3          0.2  setosa     0.680851
3           4.6          3.1           1.5          0.2  setosa     0.673913
4           5.0          3.6           1.4          0.2  setosa     0.720000

In [100]:
DataIris.assign(Sepal_ratio=lambda x : x['Sepal.Width']/x['Sepal.Length'] ).head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  Sepal_ratio
0           5.1          3.5           1.4          0.2  setosa     0.686275
1           4.9          3.0           1.4          0.2  setosa     0.612245
2           4.7          3.2           1.3          0.2  setosa     0.680851
3           4.6          3.1           1.5          0.2  setosa     0.673913
4           5.0          3.6           1.4          0.2  setosa     0.720000

In [101]:
import pandas as pd
dfa=pd.DataFrame({"A":[1,2,3],"B":[4,5,6]})
dfa.assign(C = lambda x: x ["A"]+ x["B"], D = lambda x: x['A'] + x['C'])

A  B  C   D
0  1  4  5   6
1  2  5  7   9
2  3  6  9  12

In [102]:
#Indexing and Slicing
DataIris['Sepal.Length'][:5]

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: Sepal.Length, dtype: float64

In [103]:
DataIris.loc[2]

Sepal.Length       4.7
Sepal.Width        3.2
Petal.Length       1.3
Petal.Width        0.2
Species         setosa
Name: 2, dtype: object

In [104]:
df.loc['a']

one         1
bar         1
two         1
flag    False
foo      Code
New         1
Name: a, dtype: object

In [105]:
DataIris.iloc[3]

Sepal.Length       4.6
Sepal.Width        3.1
Petal.Length       1.5
Petal.Width        0.2
Species         setosa
Name: 3, dtype: object

In [106]:
df.iloc[2]

one        3
bar        3
two        3
flag    True
foo     Code
New        3
Name: c, dtype: object

In [107]:
#data alignment and arithmetic
import numpy as np
data2=pd.DataFrame(np.random.randn (10,4), columns=['A','B','C','D'])
data3=pd.DataFrame(np.random.randn (10,3), columns=['A','B','C'])

In [108]:
data2+data3

A         B         C   D
0 -1.228927  0.207422  1.207572 NaN
1  1.996804 -0.233827 -1.659913 NaN
2 -1.581963 -1.958222 -0.334379 NaN
3 -0.769504 -2.021371  1.272863 NaN
4  0.847644  0.454773  1.786387 NaN
5 -1.411930 -3.422556  0.751909 NaN
6 -0.518955 -1.343125  0.040862 NaN
7  1.898516  1.857794 -0.137437 NaN
8  1.448681 -0.916186 -0.541618 NaN
9 -0.572326 -0.173877 -2.034274 NaN

In [113]:
data2['A'].head(5)

0   -0.466739
1   -0.233009
2   -0.591911
3   -1.430538
4    0.558150
Name: A, dtype: float64

In [117]:
(data2+data3).loc[3]

A   -0.769504
B   -2.021371
C    1.272863
D         NaN
Name: 3, dtype: float64

In [118]:
(data2+data3).iloc[1:3]

A         B         C   D
1  1.996804 -0.233827 -1.659913 NaN
2 -1.581963 -1.958222 -0.334379 NaN

In [120]:
data2.head(5)

A         B         C         D
0 -0.466739  0.753734  0.733560  2.295913
1 -0.233009  0.273180 -0.716657  0.596634
2 -0.591911  0.002172 -0.000220  2.653239
3 -1.430538 -1.261686 -0.642702  0.071731
4  0.558150 -0.282606 -0.169381  0.476014

In [126]:
(data2*5+2).head(5)

A         B         C          D
0 -0.333693  5.768671  5.667802  13.479565
1  0.834956  3.365901 -1.583283   4.983171
2 -0.959556  2.010859  1.998899  15.266196
3 -5.152691 -4.308428 -1.213511   2.358657
4  4.790750  0.586970  1.153096   4.380072

In [134]:
df1=pd.DataFrame({'A':[0,0,1],'B':[0,1,1]}, dtype=bool)
df2=pd.DataFrame({'A':[1,0,0],'B':[0,1,0]}, dtype=bool)
print(df1)
print('-----------------')
print(df2)

       A      B
0  False  False
1  False   True
2   True   True
-----------------
       A      B
0   True  False
1  False   True
2  False  False


In [146]:
#df1 & df2

In [147]:
#df1 | df2

In [148]:
#(df1 ^ df2)

In [145]:
-df1

A      B
0   True   True
1   True  False
2  False  False

In [149]:
#Transposing
df[:5]

one  bar  two   flag   foo  New
a  1.0  1.0  1.0  False  Code  1.0
b  2.0  2.0  2.0  False  Code  2.0
c  3.0  3.0  3.0   True  Code  3.0
d  NaN  NaN  4.0  False  Code  NaN

In [150]:
df[:5].T

a      b     c      d
one       1      2     3    NaN
bar       1      2     3    NaN
two       1      2     3      4
flag  False  False  True  False
foo    Code   Code  Code   Code
New       1      2     3    NaN

In [153]:
#DataFrame inoperability with numpy functions
np.exp(data2).head(5)

A         B         C          D
0  0.627044  2.124920  2.082482   9.933500
1  0.792147  1.314137  0.488382   1.815996
2  0.553269  1.002174  0.999780  14.199961
3  0.239180  0.283176  0.525870   1.074367
4  1.747437  0.753817  0.844187   1.609646

In [156]:
#np.asarray(data2)

In [157]:
#console display

In [159]:
DataIris.iloc[0:8].to_string()

'   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species\n0           5.1          3.5           1.4          0.2  setosa\n1           4.9          3.0           1.4          0.2  setosa\n2           4.7          3.2           1.3          0.2  setosa\n3           4.6          3.1           1.5          0.2  setosa\n4           5.0          3.6           1.4          0.2  setosa\n5           5.4          3.9           1.7          0.4  setosa\n6           4.6          3.4           1.4          0.3  setosa\n7           5.0          3.4           1.5          0.2  setosa'

In [167]:
pd.set_option("display.max_colwidth", 30)
DataIris.iloc[0:10]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa